"""Idempotency contract: a crashed process must not double-place orders on
restart.

Two crash scenarios from the Phase 4 brief:

  1. Crash AFTER `record_pending(intent_id, payload)` but BEFORE the HTTP
     call. On restart the intent is on disk in state PENDING with
     `order_id=None`. The reconciler must surface this so the operator
     decides — it must NOT silently re-issue (the broker may have actually
     received it; we don't know).

  2. Crash AFTER the HTTP succeeded but BEFORE
     `record_submitted(intent_id, order_id)` wrote the broker order_id.
     On restart, the intent has no order_id. Same surfacing — the
     operator can look up the order on Dhan's portal and decide.

  Additionally: if a process completes both writes and then crashes,
  restart's reconciler should pull live status from /orders/{id} and
  update the intent record (PENDING -> FILLED, etc.). Re-calling
  `place_with_intent` on the same intent_id must return the cached
  order, never POST again.
"""

import json
from typing import Any

import pytest

from brokers.dhan.dhan_broker import DhanBroker
from brokers.dhan.dhan_client import DhanClient
from brokers.dhan.order_intents import INTENTS_KEY, OrderIntentStore
from core.state_store import StateStore


class _RecordingSession:
    """Records every HTTP call. Allows scripted responses + a 'crash mode'
    that raises after the call is recorded (simulating ack-not-received).
    """

    def __init__(self, responses: dict[tuple[str, str], Any]) -> None:
        self.responses = responses
        self.calls: list[dict[str, Any]] = []
        self.raise_after_call = False

    def request(self, method, url, headers=None, json=None, timeout=None):
        self.calls.append({"method": method, "path": url.split("/v2")[-1], "json": json})
        if self.raise_after_call:
            raise ConnectionError("simulated crash after request sent")
        body = self.responses.get((method, url.split("/v2")[-1]), {"orderId": "ord-stub", "orderStatus": "PENDING"})
        return _Resp(200, body)


class _Resp:
    def __init__(self, status_code, body):
        self.status_code = status_code
        self._body = body
        self.text = json.dumps(body)

    def json(self):
        return self._body


def _store(tmp_path) -> StateStore:
    s = StateStore.__new__(StateStore)
    s.path = tmp_path / "order_intents.json"
    return s


def _broker(session: _RecordingSession, tmp_path) -> DhanBroker:
    client = DhanClient(
        client_id="1100000001",
        access_token="abc",
        session=session,
        sleep=lambda _s: None,
    )
    return DhanBroker(client=client, intent_store=OrderIntentStore(_store(tmp_path)))


PAYLOAD = {
    "transactionType": "BUY",
    "exchangeSegment": "NSE_FNO",
    "productType": "INTRADAY",
    "orderType": "STOP_LOSS_MARKET",
    "validity": "DAY",
    "securityId": "49081",
    "quantity": 50,
    "disclosedQuantity": 0,
    "price": 0.0,
    "triggerPrice": 19840.0,
    "afterMarketOrder": False,
}


def test_crash_before_http_call_keeps_intent_pending(tmp_path):
    """Simulate scenario 1: record_pending succeeded, HTTP never ran.

    We pre-populate the intent store directly to simulate the state on
    disk after such a crash, then verify the reconciler surfaces the
    intent and does NOT auto-resubmit.
    """
    store = _store(tmp_path)
    store.save({
        INTENTS_KEY: {
            "NIFTY-2026-01-05-LONG-STOP": {
                "intent_id": "NIFTY-2026-01-05-LONG-STOP",
                "status": "PENDING",
                "order_id": None,
                "payload": PAYLOAD,
                "created_at": "2026-01-05T09:20:00+05:30",
                "updated_at": "2026-01-05T09:20:00+05:30",
            }
        }
    })

    session = _RecordingSession({})
    broker = DhanBroker(
        client=DhanClient(client_id="x", access_token="y", session=session, sleep=lambda _s: None),
        intent_store=OrderIntentStore(store),
    )
    unresolved = broker.reconcile_pending_intents()

    # The intent remained PENDING (no auto re-issue happened).
    assert len(unresolved) == 1
    assert unresolved[0].order_id is None
    assert unresolved[0].status == "PENDING"
    # And no HTTP traffic was generated by the reconciler.
    assert session.calls == []


def test_crash_after_http_before_status_update_reconciles_from_broker(tmp_path):
    """Simulate scenario 2: HTTP succeeded, but we never recorded the
    order_id. The intent should still be PENDING on disk with no order_id.

    Reconciler surfaces it for operator review; it must NOT call /orders/...
    because there's no order_id to query.
    """
    store = _store(tmp_path)
    store.save({
        INTENTS_KEY: {
            "NIFTY-2026-01-05-LONG-STOP": {
                "intent_id": "NIFTY-2026-01-05-LONG-STOP",
                "status": "PENDING",
                "order_id": None,
                "payload": PAYLOAD,
                "created_at": "2026-01-05T09:20:00+05:30",
                "updated_at": "2026-01-05T09:20:00+05:30",
            }
        }
    })

    session = _RecordingSession({})
    broker = DhanBroker(
        client=DhanClient(client_id="x", access_token="y", session=session, sleep=lambda _s: None),
        intent_store=OrderIntentStore(store),
    )
    unresolved = broker.reconcile_pending_intents()

    assert len(unresolved) == 1
    assert unresolved[0].order_id is None
    assert session.calls == []


def test_intent_with_order_id_reconciles_to_filled(tmp_path):
    """Scenario 3: full happy-path with a crash AFTER record_submitted.
    The intent on disk has an order_id. Restart calls /orders/{id} and
    finds it FILLED on the broker — update intent state.
    """
    store = _store(tmp_path)
    store.save({
        INTENTS_KEY: {
            "NIFTY-2026-01-05-LONG-STOP": {
                "intent_id": "NIFTY-2026-01-05-LONG-STOP",
                "status": "SUBMITTED",
                "order_id": "ord-XYZ",
                "payload": PAYLOAD,
                "created_at": "2026-01-05T09:20:00+05:30",
                "updated_at": "2026-01-05T09:20:00+05:30",
            }
        }
    })

    session = _RecordingSession({
        ("GET", "/orders/ord-XYZ"): {"orderId": "ord-XYZ", "orderStatus": "TRADED"},
    })
    broker = DhanBroker(
        client=DhanClient(client_id="x", access_token="y", session=session, sleep=lambda _s: None),
        intent_store=OrderIntentStore(store),
    )
    broker.reconcile_pending_intents()

    refreshed = broker.intent_store.get("NIFTY-2026-01-05-LONG-STOP")
    assert refreshed is not None
    assert refreshed.status == "FILLED"
    # Reconcile must NOT post a new order.
    assert all(c["method"] != "POST" for c in session.calls)


def test_replaced_call_returns_cached_without_reposting(tmp_path):
    """Place an order; call again with the same intent_id; verify no second
    POST is issued.
    """
    session = _RecordingSession({
        ("POST", "/orders"): {"orderId": "ord-A", "orderStatus": "PENDING"},
        ("GET", "/orders/ord-A"): {"orderId": "ord-A", "orderStatus": "PENDING"},
    })
    broker = _broker(session, tmp_path)

    broker.place_market_order(
        symbol="NIFTY", side="LONG", quantity=50,
        intent_id="NIFTY-2026-01-05-LONG-MKT",
        security_id="49081", exchange_segment="NSE_FNO",
    )
    broker.place_market_order(
        symbol="NIFTY", side="LONG", quantity=50,
        intent_id="NIFTY-2026-01-05-LONG-MKT",
        security_id="49081", exchange_segment="NSE_FNO",
    )

    posts = [c for c in session.calls if c["method"] == "POST"]
    assert len(posts) == 1, "Same intent_id must not re-POST"


def test_intent_persisted_before_http_call(tmp_path):
    """The intent must hit disk BEFORE the HTTP call, otherwise a crash
    mid-call leaves no breadcrumb. We force the HTTP call to crash and
    verify the intent is on disk as PENDING.
    """
    session = _RecordingSession({})
    session.raise_after_call = True
    broker = _broker(session, tmp_path)

    with pytest.raises(ConnectionError):
        broker.place_market_order(
            symbol="NIFTY", side="LONG", quantity=50,
            intent_id="NIFTY-2026-01-05-LONG-MKT",
            security_id="49081", exchange_segment="NSE_FNO",
        )

    # Intent must exist on disk in PENDING state with no order_id.
    intent = broker.intent_store.get("NIFTY-2026-01-05-LONG-MKT")
    assert intent is not None
    assert intent.status == "PENDING"
    assert intent.order_id is None
